# Generated by Django 6.0.1 on 2026-02-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_patient_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='ai_insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
