# Generated by Django 6.0.1 on 2026-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_screening_ai_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='albumin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='alt_sgpt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='ast_sgot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='blood_urea_nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='chloride',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='creatinine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='hemoglobin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='platelet_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='rbc_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='total_bilirubin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='wbc_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
